mailing_service/urls.py
from django.urls import path
from . import views

app_name = "mailing_service"

urlpatterns = [
    path("", views.mailing_list, name="mailing_list"),  # Список рассылок
    path("create/", views.mailing_create, name="mailing_create"),  # Создание рассылки
    path(
        "<int:pk>/", views.mailing_detail, name="mailing_detail"
    ),  # Просмотр деталей рассылки
    path(
        "<int:pk>/update/", views.mailing_update, name="mailing_update"
    ),  # Редактирование рассылки
    path(
        "<int:pk>/delete/", views.mailing_delete, name="mailing_delete"
    ),  # Удаление рассылки
    path("report/", views.mailing_report, name="mailing_report"),  # Отчет о рассылках
]

my_store/urls.py
"""
URL configuration for the my_store project.
"""

from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.decorators.cache import cache_page
from products.views import ProductDetailView  # Импортируем ProductDetailView

urlpatterns = [
    path("admin/", admin.site.urls),  # Подключение админки
    path("", include("products.urls")),  # Подключаем маршруты из приложения products
    path("users/", include("users.urls")),  # Подключаем маршруты из приложения users
    path(
        "mailings/", include("mailing_service.urls")
    ),  # Подключаем маршруты из приложения mailing_service
    path(
        "product/<slug:slug>/",
        cache_page(60 * 15)(ProductDetailView.as_view()),
        name="product_detail",
    ),  # Добавляем кеширование
]

# Добавляем поддержку медиафайлов и статических файлов в режиме разработки
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from .views import (
    register,
    CustomLoginView,
    reset_password,
    edit_profile,
    verify_email,
    email_sent,
    user_create,  # Добавляем представление для создания пользователя
    user_list,  # Добавляем представление для списка пользователей
    user_delete,  # Добавляем представление для удаления пользователя
    user_update,  # Добавляем представление для редактирования пользователя
)
from django.contrib.auth.views import LogoutView

app_name = "users"

urlpatterns = [
    path("register/", register, name="register"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("reset_password/", reset_password, name="reset_password"),
    path("profile/edit/", edit_profile, name="edit_profile"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("verify-email/<uidb64>/<token>/", verify_email, name="verify_email"),
    path("email-sent/", email_sent, name="email_sent"),
    path("create/", user_create, name="user_create"),  # Создание пользователя
    path("list/", user_list, name="user_list"),  # Список пользователей
    path("<int:pk>/delete/", user_delete, name="user_delete"),  # Удаление пользователя
    path(
        "<int:pk>/update/", user_update, name="user_update"
    ),  # Редактирование пользователя
]

mailing_service/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.core.exceptions import ValidationError


class Client(models.Model):
    email = models.EmailField(unique=True, verbose_name="Электронная почта")
    name = models.CharField(max_length=100, verbose_name="Имя")
    full_name = models.CharField(max_length=255, verbose_name="Полное имя")
    comment = models.TextField(blank=True, null=True, verbose_name="Комментарий")
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="clients",
        verbose_name="Владелец",
    )

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"

    def __str__(self):
        return self.email


class Message(models.Model):
    subject = models.CharField(max_length=255, verbose_name="Тема")
    body = models.TextField(verbose_name="Текст сообщения")
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="messages",
        verbose_name="Владелец",
    )

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"

    def __str__(self):
        return self.subject


class Mailing(models.Model):
    STATUS_CHOICES = [
        ("created", "Создана"),
        ("running", "Запущена"),
        ("completed", "Завершена"),
    ]
    start_date = models.DateTimeField(default=timezone.now, verbose_name="Дата начала")
    periodicity = models.CharField(
        max_length=10,
        choices=[("day", "Ежедневно"), ("week", "Еженедельно")],
        default="day",
        verbose_name="Периодичность",
    )
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default="created", verbose_name="Статус"
    )
    message = models.OneToOneField(
        Message, on_delete=models.CASCADE, verbose_name="Сообщение"
    )
    clients = models.ManyToManyField(Client, verbose_name="Клиенты")
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="mailings",
        verbose_name="Владелец",
    )

    def clean(self):
        # Проверка на то, что дата начала рассылки в будущем
        if self.start_date <= timezone.now():
            raise ValidationError("Дата начала рассылки должна быть в будущем.")

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"

    def __str__(self):
        return f"{self.message.subject} - {self.get_status_display()}"


class MailingAttempt(models.Model):
    mailing = models.ForeignKey(
        Mailing, on_delete=models.CASCADE, verbose_name="Рассылка"
    )
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Время попытки")
    status = models.CharField(
        max_length=10,
        choices=[("success", "Успешно"), ("failure", "Неуспешно")],
        verbose_name="Статус",
    )
    response = models.TextField(verbose_name="Ответ")

    class Meta:
        verbose_name = "Попытка рассылки"
        verbose_name_plural = "Попытки рассылки"

    def __str__(self):
        return f"Attempt for {self.mailing} at {self.timestamp} - Status: {self.status}"

mailing_service/forms.py
from django import forms
from .models import Mailing, Message, Client


class MailingForm(forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ["start_date", "periodicity", "status", "message", "clients"]
        widgets = {
            "start_date": forms.DateTimeInput(
                attrs={"class": "form-control", "type": "datetime-local"}
            ),
            "periodicity": forms.Select(attrs={"class": "form-control"}),
            "status": forms.Select(attrs={"class": "form-control"}),
            "message": forms.Select(attrs={"class": "form-control"}),
            "clients": forms.SelectMultiple(attrs={"class": "form-control"}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def clean_message(self):
        message = self.cleaned_data.get("message")
        if not message:
            raise forms.ValidationError("Поле 'Сообщение' не может быть пустым.")
        return message

    def clean_clients(self):
        clients = self.cleaned_data.get("clients")
        if not clients:
            raise forms.ValidationError(
                "Необходимо выбрать хотя бы одного клиента для рассылки."
            )
        return clients


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ["subject", "body"]
        widgets = {
            "subject": forms.TextInput(attrs={"class": "form-control"}),
            "body": forms.Textarea(attrs={"class": "form-control"}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ["email", "name", "comment"]
        widgets = {
            "email": forms.EmailInput(
                attrs={"class": "form-control", "placeholder": "Введите email"}
            ),
            "name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Введите имя"}
            ),
            "comment": forms.Textarea(
                attrs={"class": "form-control", "placeholder": "Добавьте комментарий"}
            ),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if Client.objects.filter(email=email).exists():
            raise forms.ValidationError("Пользователь с таким email уже существует.")
        return email

mailing_service/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from .models import Mailing
from .forms import MailingForm
from django.views.decorators.cache import cache_page
from django.contrib.auth.models import User


# Список рассылок
@cache_page(60 * 15)  # Кешировать на 15 минут
@login_required
def mailing_list(request):
    if request.user.is_staff:
        mailings = Mailing.objects.all()  # Менеджеры видят все рассылки
    else:
        mailings = Mailing.objects.filter(
            owner=request.user
        )  # Пользователи видят только свои рассылки
    return render(request, "mailing_service/mailing_list.html", {"mailings": mailings})


# Просмотр деталей рассылки
@cache_page(60 * 15)  # Кешировать на 15 минут
@login_required
def mailing_detail(request, pk):
    mailing = get_object_or_404(Mailing, pk=pk)
    if not (request.user.is_staff or mailing.owner == request.user):
        return redirect(
            "mailing_service:mailing_list"
        )  # Запретить доступ к чужим рассылкам
    return render(request, "mailing_service/mailing_detail.html", {"mailing": mailing})


# Создание новой рассылки
@cache_page(60 * 15)  # Кешировать на 15 минут
@login_required
def mailing_create(request):
    if request.method == "POST":
        form = MailingForm(request.POST)
        if form.is_valid():
            mailing = form.save(commit=False)
            mailing.owner = request.user  # Привязываем рассылку к текущему пользователю
            mailing.save()
            messages.success(request, "Рассылка успешно создана!")
            return redirect("mailing_service:mailing_list")
        else:
            messages.error(
                request,
                "Ошибка при создании рассылки. Проверьте корректность введенных данных.",
            )
    else:
        form = MailingForm()
    return render(request, "mailing_service/mailing_form.html", {"form": form})


# Редактирование рассылки
@cache_page(60 * 15)  # Кешировать на 15 минут
@login_required
def mailing_update(request, pk):
    mailing = get_object_or_404(Mailing, pk=pk)
    if not (request.user.is_staff or mailing.owner == request.user):
        return redirect(
            "mailing_service:mailing_list"
        )  # Запретить доступ к чужим рассылкам
    if request.method == "POST":
        form = MailingForm(request.POST, instance=mailing)
        if form.is_valid():
            form.save()
            messages.success(request, "Рассылка успешно обновлена!")
            return redirect("mailing_service:mailing_detail", pk=pk)
        else:
            messages.error(
                request,
                "Ошибка при обновлении рассылки. Проверьте корректность введенных данных.",
            )
    else:
        form = MailingForm(instance=mailing)
    return render(request, "mailing_service/mailing_form.html", {"form": form})


# Удаление рассылки
@cache_page(60 * 15)  # Кешировать на 15 минут
@login_required
def mailing_delete(request, pk):
    mailing = get_object_or_404(Mailing, pk=pk)
    if not (request.user.is_staff or mailing.owner == request.user):
        return redirect(
            "mailing_service:mailing_list"
        )  # Запретить доступ к чужим рассылкам
    if request.method == "POST":
        mailing.delete()
        messages.success(request, "Рассылка успешно удалена!")
        return redirect("mailing_service:mailing_list")

    # Запрос подтверждения удаления
    return render(
        request, "mailing_service/mailing_confirm_delete.html", {"mailing": mailing}
    )


# Дашборд для менеджеров
@cache_page(60 * 15)  # Кешировать на 15 минут
@user_passes_test(lambda u: u.is_staff)  # Доступ только для менеджеров
def manager_dashboard(request):
    mailings = Mailing.objects.all()  # Менеджер видит все рассылки
    users = User.objects.all()  # Менеджер видит всех пользователей
    return render(
        request, "manager/dashboard.html", {"mailings": mailings, "users": users}
    )


# Отчет проведенных рассылок
@login_required
def mailing_report(request):
    mailings = Mailing.objects.filter(
        owner=request.user
    )  # Получаем рассылки текущего пользователя
    return render(
        request, "mailing_service/mailing_report.html", {"mailings": mailings}
    )

mailing_service/templates/mailing_service/mailing_confirm_delete.html
<h1>Удалить рассылку "{{ mailing.message.subject }}"?</h1>
<p>Вы уверены, что хотите удалить эту рассылку? Это действие нельзя отменить.</p>
<p><strong>Тема сообщения:</strong> {{ mailing.message.subject }}</p>
<p><strong>Дата начала:</strong> {{ mailing.start_date|date:"d-m-Y H:i" }}</p>

<form method="post" class="mb-3">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Удалить рассылку</button>
</form>

<div>
    <a href="{% url 'mailing_service:mailing_detail' mailing.pk %}" class="btn btn-secondary">Отмена</a>
    <a href="{% url 'mailing_service:mailing_list' %}" class="btn btn-light">Назад к списку рассылок</a>
</div>

{% if mailing.clients.exists %}
    <div class="mt-4">
        <h4>Клиенты, связанные с этой рассылкой:</h4>
        <ul>
            {% for client in mailing.clients.all %}
                <li>{{ client.email }} ({{ client.name }})</li>
            {% endfor %}
        </ul>
    </div>
{% else %}
    <p>Нет клиентов, связанных с этой рассылкой.</p>
{% endif %}

mailing_service/templates/mailing_service/mailing_detail.html
<h1>Детали рассылки</h1>
<div class="mb-4">
    <p><strong>Тема:</strong> {{ mailing.message.subject }}</p>
    <p><strong>Текст:</strong> {{ mailing.message.body }}</p>
    <p><strong>Статус:</strong> {{ mailing.get_status_display }}</p>
    <p><strong>Дата начала:</strong> {{ mailing.start_date|date:"d-m-Y H:i" }}</p>
    <p><strong>Периодичность:</strong> {{ mailing.get_periodicity_display }}</p>
</div>

<div class="mb-4">
    <h3>Клиенты:</h3>
    {% if mailing.clients.exists %}
        <ul class="list-group">
            {% for client in mailing.clients.all %}
                <li class="list-group-item">{{ client.email }} ({{ client.name }})</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Нет клиентов для этой рассылки.</p>
    {% endif %}
</div>

<div class="mb-4">
    <a href="{% url 'mailing_service:mailing_update' mailing.pk %}" class="btn btn-warning">Редактировать</a>
    <a href="{% url 'mailing_service:mailing_delete' mailing.pk %}" class="btn btn-danger">Удалить</a>
    <a href="{% url 'mailing_service:mailing_list' %}" class="btn btn-secondary">Назад к списку</a>
</div>

mailing_service/templates/mailing_service/mailing_form.html
{% extends 'products/base.html' %}

{% block title %}{{ mailing.subject|default:"Создание рассылки" }}{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>{{ mailing.subject|default:"Создание рассылки" }}</h2>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group">
            <label for="subject">Тема рассылки:</label>
            <input type="text" name="subject" class="form-control" id="subject" value="{{ mailing.subject|default:'' }}" required>
        </div>

        <div class="form-group">
            <label for="message">Сообщение:</label>
            <textarea name="message" class="form-control" id="message" rows="5" required>{{ mailing.message.body|default:'' }}</textarea>
        </div>

        <div class="form-group">
            <label for="start_date">Дата начала:</label>
            <input type="datetime-local" name="start_date" class="form-control" id="start_date" value="{{ mailing.start_date|date:'Y-m-d\TH:i'|default:'' }}" required>
        </div>

        <div class="form-group">
            <label for="periodicity">Периодичность:</label>
            <select name="periodicity" class="form-control" id="periodicity" required>
                <option value="day" {% if mailing.periodicity == 'day' %}selected{% endif %}>Ежедневно</option>
                <option value="week" {% if mailing.periodicity == 'week' %}selected{% endif %}>Еженедельно</option>
            </select>
        </div>

        <button type="submit" class="btn btn-success">{{ mailing.subject|default:"Создать рассылку" }}</button>
    </form>

    <a href="{% url 'mailing_service:mailing_list' %}" class="btn btn-secondary mt-3">Назад к списку рассылок</a>
</div>
{% endblock %}

mailing_service/templates/mailing_service/mailing_list.html
<h1>Список рассылок</h1>

<a href="{% url 'mailing_service:mailing_create' %}" class="btn btn-primary mb-3">Создать рассылку</a>

<ul class="list-group mb-4">
    {% for mailing in mailings %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <a href="{% url 'mailing_service:mailing_detail' mailing.pk %}" class="text-decoration-none">
                {{ mailing.message.subject }} - Статус: {{ mailing.get_status_display }}
            </a>
            <div>
                <a href="{% url 'mailing_service:mailing_update' mailing.pk %}" class="btn btn-warning btn-sm">Изменить</a>
                <a href="{% url 'mailing_service:mailing_delete' mailing.pk %}" class="btn btn-danger btn-sm ml-2">Удалить</a>
            </div>
        </li>
    {% empty %}
        <li class="list-group-item">Нет рассылок.</li>
    {% endfor %}
</ul>

<div class="alert alert-info" role="alert">
    <strong>Совет:</strong> Если вы не видите свои рассылки, убедитесь, что вы создали их ранее!
</div>

mailing_service/templates/mailing_service/mailing_report.html
{% extends 'products/base.html' %}

{% block title %}Отчет о рассылках{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>Отчет о рассылках</h2>

    {% if mailings %}
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Тема рассылки</th>
                <th>Статус</th>
                <th>Дата начала</th> <!-- Изменено на "Дата начала" -->
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
            {% for mailing in mailings %}
            <tr>
                <td>{{ mailing.id }}</td>
                <td>{{ mailing.message.subject }}</td> <!-- Изменено на сообщение -->
                <td>{{ mailing.get_status_display }}</td> <!-- Используем метод получения статуса -->
                <td>{{ mailing.start_date|date:"d-m-Y H:i" }}</td> <!-- Форматируем дату начала -->
                <td>
                    <a href="{% url 'mailing_service:mailing_detail' mailing.pk %}" class="btn btn-info">Просмотреть</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <div class="alert alert-warning" role="alert">
        Рассылки отсутствуют.
    </div>
    {% endif %}
</div>
{% endblock %}